[project]
name = "dj-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.7",
    "django-cleanup>=9.0.0",
    "django-crispy-forms>=2.4",
    "pillow>=12.0.0",
]
